server:
  port: 8881

spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ****
            client-secret: ****
        provider:
          okta:
            authorization-uri: https://dev-902988.okta.com/oauth2/v1/authorize
            token-uri: https://dev-902988.okta.com/oauth2/v1/token
            user-info-uri: https://dev-902988.okta.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://dev-902988.okta.com/oauth2/v1/keys